# Service === this repo service => consumer of the service, 
# otherwise it will be published in another repo
# SERVICE
SERVICE = "schedule_mcp"
PERSONAL_SCHEDULE_SERVICE = "personal_schedule"
NOTIFICATION_SERVICE = "notification"

# FEATURE
WORK_GENERATION = "generate_work"
WORK_TRANSFER = "transfer_work"
TEAM = "team"
AI = "ai"
SPRINT_GENERATION = "sprint-generation"

# EXCHANGE
EXCHANGE = "exchange"
WORK_GENERATION_EXCHANGE = f"{SERVICE}_{WORK_GENERATION}_{EXCHANGE}"
WORK_TRANSFER_EXCHANGE = f"{PERSONAL_SCHEDULE_SERVICE}_{WORK_TRANSFER}_{EXCHANGE}"
NOTIFICATION_GENERATE_WORK_EXCHANGE = f"{NOTIFICATION_SERVICE}_{WORK_GENERATION}_{EXCHANGE}"

# AI sprint generation exchanges (LLD)
NOTIFICATION_TEAM_EXCHANGE = f"{NOTIFICATION_SERVICE}_{TEAM}_{EXCHANGE}"
AI_TEAM_EXCHANGE = f"{AI}_{TEAM}_{EXCHANGE}"
TEAM_AI_EXCHANGE = f"{TEAM}_{AI}_{EXCHANGE}"

# QUEUE
QUEUE = "queue"
WORK_GENERATION_QUEUE = f"{SERVICE}_{WORK_GENERATION}_{QUEUE}"
WORK_TRANSFER_QUEUE = f"{PERSONAL_SCHEDULE_SERVICE}_{WORK_TRANSFER}_{QUEUE}"

# AI sprint generation queues (LLD)
NOTIFICATION_TEAM_QUEUE = f"{NOTIFICATION_SERVICE}_{TEAM}_{QUEUE}"
AI_TEAM_SPRINT_GENERATION_QUEUE = f"{AI}_{TEAM}_{SPRINT_GENERATION}_{QUEUE}"
TEAM_AI_SPRINT_GENERATION_RESULT_QUEUE = f"{TEAM}_{AI}_{SPRINT_GENERATION}-result_{QUEUE}"

# ROUTING KEY
WORK_GENERATION_ROUTING_KEY = f"{SERVICE}_{WORK_GENERATION}"
WORK_TRANSFER_ROUTING_KEY = f"{PERSONAL_SCHEDULE_SERVICE}_{WORK_TRANSFER}"
NOTIFICATION_GENERATE_WORK_ROUTING_KEY = f"{NOTIFICATION_SERVICE}_{WORK_GENERATION}"

# AI sprint generation routing keys (LLD)
NOTIFICATION_TEAM_ROUTING_KEY = f"{NOTIFICATION_SERVICE}_{TEAM}"
AI_TEAM_SPRINT_GENERATION_ROUTING_KEY = f"{AI}_{TEAM}_{SPRINT_GENERATION}"
TEAM_AI_SPRINT_GENERATION_RESULT_ROUTING_KEY = f"{TEAM}_{AI}_{SPRINT_GENERATION}-result"