# Service === this repo service => consumer of the service, 
# otherwise it will be published in another repo
# SERVICE
SERVICE = "schedule_mcp"
PERSONAL_SCHEDULE_SERVICE = "personal_schedule"
NOTIFICATION_SERVICE = "notification"

# FEATURE
WORK_GENERATION = "generate_work"
WORK_TRANSFER = "transfer_work"

# EXCHANGE
EXCHANGE = "exchange"
WORK_GENERATION_EXCHANGE = f"{SERVICE}_{WORK_GENERATION}_{EXCHANGE}"
WORK_TRANSFER_EXCHANGE = f"{PERSONAL_SCHEDULE_SERVICE}_{WORK_TRANSFER}_{EXCHANGE}"
NOTIFICATION_GENERATE_WORK_EXCHANGE = f"{NOTIFICATION_SERVICE}_{WORK_GENERATION}_{EXCHANGE}"

# QUEUE
QUEUE = "queue"
WORK_GENERATION_QUEUE = f"{SERVICE}_{WORK_GENERATION}_{QUEUE}"
WORK_TRANSFER_QUEUE = f"{PERSONAL_SCHEDULE_SERVICE}_{WORK_TRANSFER}_{QUEUE}"

# ROUTING KEY
WORK_GENERATION_ROUTING_KEY = f"{SERVICE}_{WORK_GENERATION}"
WORK_TRANSFER_ROUTING_KEY = f"{PERSONAL_SCHEDULE_SERVICE}_{WORK_TRANSFER}"
NOTIFICATION_GENERATE_WORK_ROUTING_KEY = f"{NOTIFICATION_SERVICE}_{WORK_GENERATION}"